### ISSUE TITLE
Can we show file save dialog to export a file?

### ISSUE THREAD

**Issue by reysantana** [yasirkula/UnityNativeFilePicker#10]
I am going to export a file to a user-specific path.
I want the user to pick a folder to save the file to that folder.
Is this possible with this plugin?

**Comment by yasirkula** [comment]
Unfortunately not. But you can use SimpleFileBrowser for it, if you wish: https://github.com/yasirkula/UnitySimpleFileBrowser

**Comment by reysantana** [comment]
Thank you so much for your quick help!
By the way, does SimpleFileBrowser work on iOS devices?

**Comment by yasirkula** [comment]
You can browse directories iOS allows but most directories are blocked.

**Comment by reysantana** [comment]
thank you so much!
