### ISSUE TITLE
PlayerPrefs.GetInt can only be called in the main thread

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [yasirkula/UnityNativeFilePicker#11]
Hi!
I think the error is due to the fact that the WebView on Andoid is launched on a different thread, and I am listening to the FileSelectionRequested event in which I am launching the NativeFilePicker. 

![image](https://user-images.githubusercontent.com/30652592/116046832-bac73780-a673-11eb-9a93-7f6b30d31dd3.png)
![image](https://user-images.githubusercontent.com/30652592/116046909-d0d4f800-a673-11eb-9f5a-cdbce72522c4.png)

**Comment by yasirkula** [comment]
Yes, you must call NativeFilePicker functions from the main thread. There is no workaround for this, unfortunately.
