### ISSUE TITLE
Issue with AdMob on iOS

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeFilePicker#14]
**Description of the bug**

Hi! For some reason, AdMob rewarded ads block further usage of NativeFilePicker.ExportFile. At the same NativeFilePicker.ExportFile works as expected if I don't run AdMob ads. This happens only on iOS. It works fine on Android.

**Reproduction steps**

1) Launch AdMob rewarded ad
2) Watch and complete it
3) Make sure that NativeFilePicker.CanExportFiles()=True, NativeFilePicker.IsFilePickerBusy()=False (OK)
4) Launch NativeFilePicker.ExportFile with any file from RewardedAd.OnUserEarnedReward callback (FilePicker doesn't appear and is not visible)
5) Any further calls to NativeFilePicker.IsFilePickerBusy() return True

**Platform specs**

Latest asset version, Unity 2020.3.14, iOS 14.7.1

**Additional info**

Nothing interesting found in iOS/Xcode logs.

**Comment by hippogamesunity** [comment]
I've found some related info
![image](https://user-images.githubusercontent.com/7318172/137150830-b0aa4ad7-a533-4fe3-9a2c-c9ec684a2f42.png)

**Comment by yasirkula** [comment]
1. Does showing file picker 2 times in a row without displaying rewarded ad work correctly?
2. Are there any error messages in logcat/Xcode console?

**Comment by hippogamesunity** [comment]
Well, I can run AdMob separately, and after this NativeFilePicker works fine. I decided to workaround this by removing ads to access some app features on ios.
I understand this issue is minor and it's hard to debug it. Let's close it and leave this for history =) Thanks anyway!
