### ISSUE TITLE
Question about opening files of custom extensions on Android

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeFilePicker#16]
Hello! allowedFileTypes should be a known MIME on Android. All of my custom extension registered in [NativeFilePicker Custom Types] can't be picked on Android 11 (they are grayed).
![image](https://user-images.githubusercontent.com/7318172/142690546-1374d025-0983-4d2f-b7db-43922d80d5a8.png)
The only possible workaround I've found is using "application/octet-stream"
```
allowedFileTypes.Add("application/octet-stream");
```
The problem is that Android 11 creates a new file duplicate in the app's temp storage (where this file is accessible), but its' extension in ".bin". So I'm wondering is there any way to know the original file path? For now I have to try all possible extensions int try/catch block to read ".bin" files.

**Comment by hippogamesunity** [comment]
Oh, sorry, I've found it. Android just adds .bin to the original file name, so it becomes goblin.psp.bin.
Anyway, I think you can add "application/octet-stream" to the manual.

**Comment by yasirkula** [comment]
I'll come up with a solution.

**Comment by yasirkula** [comment]
Does **NativeFilePicker.aar** inside [this zip archive](https://github.com/yasirkula/UnityNativeFilePicker/files/7576153/NativeFilePicker.zip) resolve the issue?

**Comment by yasirkula** [comment]
@hippogamesunity

**Comment by hippogamesunity** [comment]
Oh, sorry, I've missed your reply. I'll check this asap.

**Comment by hippogamesunity** [comment]
No, it's not working
![Screenshot_20211127-162124_Files](https://user-images.githubusercontent.com/7318172/143683247-ef1b6ed8-f50e-455e-bb1c-c3f11e71dbe0.jpg)
![image](https://user-images.githubusercontent.com/7318172/143683262-a9c9d225-5fb5-4e5b-8171-6fd9f318fc6a.png)

**Comment by yasirkula** [comment]
It's impossible to introduce custom extensions on Android but I was talking about **.bin** getting appended to the returned filenames :) Is it resolved?

**Comment by hippogamesunity** [comment]
Oh, let me check.

**Comment by hippogamesunity** [comment]
Yes, it doesn't add .bin anymore.
