### ISSUE TITLE
How to run on the macOS(x86) runtime?

### ISSUE THREAD

**Issue by RadioDisney** [yasirkula/UnityNativeFilePicker#17]
How to run the macOS(x86) runtime?

UnityEditor.EditorUtility.OpenFilePanelWithFilters

This function don't building on the plantform with macOS.

**Comment by yasirkula** [comment]
This plugin supports only Android & iOS. Although the native source code for iOS might largely apply to MacOS, there are probably some differences between iOS and MacOS so the code won't work without modifications probably. You can use one of these plugins, if you wish:

- https://github.com/gkngkc/UnityStandaloneFileBrowser
- https://github.com/yasirkula/UnitySimpleFileBrowser
