### ISSUE TITLE
Android: java.lang.NumberFormatException: For input string: "msf:56534"

### ISSUE THREAD

**Issue by dzak83** [yasirkula/UnityNativeFilePicker#18]
**Description of the bug**

NumberFormatException when picking up the file on Android

**Reproduction steps**

Exception during zip file picking from Downloads folder on Android and app crash right after it.

**Code to repro**
```
        var fileTypes = NativeFilePicker.ConvertExtensionToFileType("zip");        
        NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) =>
        {
            if (path == null)
            {
                Debug.Log("Operation cancelled");
            }
            else
            {
                Debug.Log("Picked file: " + path);

               // do stuff with file
            }
        }, new string[] { fileTypes });

        Debug.Log("Permission result: " + permission);
```

**Logs for the above**

```
01-11 00:02:11.374  6678  6706 I Unity   : Permission result: Granted

01-11 00:02:14.542  6678  6829 D Unity   : Selected media uri: content://com.android.providers.downloads.documents/document/msf%3A56534
01-11 00:02:14.545  6678  6829 E Unity   : Exception:
01-11 00:02:14.545  6678  6829 E Unity   : java.lang.NumberFormatException: For input string: "msf:56534"
01-11 00:02:14.545  6678  6829 E Unity   :      at java.lang.Long.parseLong(Long.java:594)
01-11 00:02:14.545  6678  6829 E Unity   :      at java.lang.Long.valueOf(Long.java:808)
01-11 00:02:14.545  6678  6829 E Unity   :      at com.yasirkula.unity.NativeFilePickerUtils.GetPathFromURI(NativeFilePickerUtils.java:107)
01-11 00:02:14.545  6678  6829 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultOperation.getPathFromURI(NativeFilePickerPickResultOperation.java:126)
01-11 00:02:14.545  6678  6829 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultOperation.execute(NativeFilePickerPickResultOperation.java:53)
01-11 00:02:14.545  6678  6829 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultFragment$1.run(NativeFilePickerPickResultFragment.java:49)
01-11 00:02:14.545  6678  6829 E Unity   :      at java.lang.Thread.run(Thread.java:923)
```

Any suggestions? I think it worked before so maybe I just got a weird file?

**Comment by yasirkula** [comment]
This affects multiple of my plugins, thanks for reporting it.

**Comment by dzak83** [comment]
> This affects multiple of my plugins, thanks for reporting it.

Do you have any ideas for the workaround? Try/Catch didn't seem to help. App is still crashing.

**Comment by dzak83** [comment]
Also, is there a way I can try to build your aar and debug the problem? Maybe I can help? I saw .github folder with some Android code.

**Comment by dzak83** [comment]
@yasirkula I am attaching also a file that gives me a repro

Repro steps:
1. Copy this file to Download folder on Android device (I am using Pixel 2)
2. Run the code:
```
        var fileTypes = NativeFilePicker.ConvertExtensionToFileType("zip");        
        NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) =>
        {
            if (path == null)
            {
                Debug.Log("Operation cancelled");
            }
            else
            {
                Debug.Log("Picked file: " + path);

               // do stuff with file
            }
        }, new string[] { fileTypes });

        Debug.Log("Permission result: " + permission);
```

[ReproFile.zip](https://github.com/yasirkula/UnityNativeFilePicker/files/7851549/ReproFile.zip)

**Comment by yasirkula** [comment]
Try-catch will need to be added to the native code I guess. You can build AARs in Android Studio by creating a new project, settings its type to library project and then copying my native source files and building it. Then you should swap NativeFilePicker.aar's classes.jar file with the one inside the AAR you've generated.

**Comment by dzak83** [comment]
> Now that I think about it, the crash can't be caused by NumberFormatException because it's [catched](https://github.com/yasirkula/UnityNativeFilePicker/blob/13c83a8d6b726a1a389fa6eae986d3fb31bf5129/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeFilePickerUtils.java#L162-L166) (you can see the word "Exception:" in the logs you've posted). Are there any other errors? Can your app crash when returned path is somehow null (or maybe the returned path isn't null at all, you can put Debug.Logs to test it)?

I double checked and I don't see any other place.
logcat results (_Adb.exe logcat -s Unity DEBUG_):
![image](https://user-images.githubusercontent.com/27939815/149273229-c0214ba5-e42b-4346-a8db-00b98edbe4ff.png)

Repro on this method:
![image](https://user-images.githubusercontent.com/27939815/149273308-8897e39a-2bf5-4c27-9dd3-05080c18acb6.png)
called from here:
![image](https://user-images.githubusercontent.com/27939815/149273355-7030c9e2-3280-435b-b5c4-182a0d3a97ff.png)

which was invoked from Unity UI button, so no background threads.

Did you get local repro with the zip I shared above?

**Comment by yasirkula** [comment]
This issue won't happen on my phone because it uses an older Android version but I'll try it on an emulator.

**Comment by dzak83** [comment]
If you have a version of aar that you want me to try, I am happy to do it too. Maybe with more logging or potential fixes? 

I didn't have yet time to build aar myself and try things.

**Comment by yasirkula** [comment]
No matter what I try, I can't run ARM64 emulators on Windows 64-bit (_Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host_). Latest x86 emulators require me to use a Unity version that isn't very old and supports x86 export and I guess I'm lazy to download one such Unity version right now :D

Could you run logcat without any filters and check out the crash message/stacktrace? I think that information will prove useful.

**Comment by dzak83** [comment]
Sure. Here is was I see extra on top of that exception above. Notice second stacktrace for "Animators may only be run on Looper threads"

```
01-13 17:13:04.844  1031  1094 I CHRE    : @ 1926896.910: [NanoMinion] sent MSG Type 0x3, Version 0, 50 bytes, MessageId 255
01-13 17:13:04.844  1031  1094 I CHRE    : @ 1926896.911: [ChreWifiScanner] Requested active scan, interval: 120s, Max Age 20s
01-13 17:13:04.844  1031  1094 I CHRE    : @ 1926896.911: [ChreWifiScanner] active scan # 1086 started
01-13 17:13:06.050 20308 20633 D Unity   : Selected media uri: content://com.android.providers.downloads.documents/document/msf%3A56534
01-13 17:13:06.059 20308 20633 E Unity   : Exception:
01-13 17:13:06.059 20308 20633 E Unity   : java.lang.NumberFormatException: For input string: "msf:56534"
01-13 17:13:06.059 20308 20633 E Unity   : 	at java.lang.Long.parseLong(Long.java:594)
01-13 17:13:06.059 20308 20633 E Unity   : 	at java.lang.Long.valueOf(Long.java:808)
01-13 17:13:06.059 20308 20633 E Unity   : 	at com.yasirkula.unity.NativeFilePickerUtils.GetPathFromURI(NativeFilePickerUtils.java:107)
01-13 17:13:06.059 20308 20633 E Unity   : 	at com.yasirkula.unity.NativeFilePickerPickResultOperation.getPathFromURI(NativeFilePickerPickResultOperation.java:126)
01-13 17:13:06.059 20308 20633 E Unity   : 	at com.yasirkula.unity.NativeFilePickerPickResultOperation.execute(NativeFilePickerPickResultOperation.java:53)
01-13 17:13:06.059 20308 20633 E Unity   : 	at com.yasirkula.unity.NativeFilePickerPickResultFragment$1.run(NativeFilePickerPickResultFragment.java:49)
01-13 17:13:06.059 20308 20633 E Unity   : 	at java.lang.Thread.run(Thread.java:923)
01-13 17:13:06.086  5702 11093 I MediaProvider: Open with lower FS for /storage/emulated/0/Download/HomeData.zip. Uid: 10021
01-13 17:13:06.138 15646 15660 W System  : A resource failed to call release. 
01-13 17:13:06.157 20308 20632 E AndroidRuntime: FATAL EXCEPTION: Timer-0
01-13 17:13:06.157 20308 20632 E AndroidRuntime: Process: com.App, PID: 20308
01-13 17:13:06.157 20308 20632 E AndroidRuntime: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at android.animation.AnimatorSet.pause(AnimatorSet.java:647)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorUI.pause(AnimatedVectorDrawable.java:1217)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at android.graphics.drawable.AnimatedVectorDrawable.setVisible(AnimatedVectorDrawable.java:492)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at android.widget.ProgressBar.swapCurrentDrawable(ProgressBar.java:691)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at android.widget.ProgressBar.setIndeterminate(ProgressBar.java:679)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at com.yasirkula.unity.NativeFilePickerPickResultFragment$3.run(NativeFilePickerPickResultFragment.java:133)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at java.util.TimerThread.mainLoop(Timer.java:562)
01-13 17:13:06.157 20308 20632 E AndroidRuntime: 	at java.util.TimerThread.run(Timer.java:512)
```

**Comment by yasirkula** [comment]
This turned out to be a different issue and that stacktrace helped me pinpoint the issue. Can you replace **Plugins/NativeFilePicker/Android/NativeFilePicker.aar** with the one inside [this zip archive](https://github.com/yasirkula/UnityNativeFilePicker/files/7870428/NativeFilePicker.zip) and see if it resolves the issue?

**Comment by dzak83** [comment]
> lePicker/Android

It worked!! The same zip is now loaded, no problems. Thank you for help! I hope I helped at least a little with investigation :)

**Comment by yasirkula** [comment]
Yes you were really helpful, thank you! I'll now push updates to all my affected assets.
