### ISSUE TITLE
Some of the selected photos are rotated + - 90 degrees

### ISSUE THREAD

**Issue by DavianMachete** [yasirkula/UnityNativeFilePicker#19]
_Hi, I really like this plugin and find it very useful. But I got a problem. I need the user to be able to choose a profile photo in the application, but after choosing in some cases, the selected photo rotates by + -90 degrees. How can I fix this? Thank you._

**Here is the code that I use:**
```C#
public void PickTheProfilePhoto()
    {
        // Don't attempt to import/export files if the file picker is already open
        if (NativeFilePicker.IsFilePickerBusy())
            return;

#if UNITY_ANDROID
        // Use MIMEs on Android
        string[] fileType = new string[] { "image/*" };
#else
	    // Use UTIs on iOS
	    string[] fileType = new string[] { "public.image" };
#endif

        // Pick image 
        NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) =>
        {
            if (path == null)
                Debug.Log("Operation cancelled");
            else
            {
                //for (int i = 0; i < path.Length; i++)
                Debug.Log("Picked file: " + path);
                Texture2D texture = new Texture2D(2, 2);
                texture.LoadImage(File.ReadAllBytes(path));
                //Set User Image
                Debug.Log($"currentUserProfile.Email is  {currentUserProfile.Email}");
                ProccessProfileImage(texture, currentUserProfile.Email);
            }
        }, fileType);

        Debug.Log("Permission result: " + permission);
    }

private void ProccessProfileImage(Texture2D texture,string _UserEmail, bool save=true)
    {
        Vector2 sizeDeltaForTexture = Vector2.one * 190f;
        if (texture.width > texture.height)
        {
            float ratio = (float)texture.width / (float)texture.height;
            sizeDeltaForTexture.x *= ratio;
        }
        else if(texture.width < texture.height)
        {
            float ratio = (float)texture.height / (float)texture.width;
            sizeDeltaForTexture.y *= ratio;
        }


        foreach (var item in profileImages)
        {
            item.gameObject.GetComponent<RectTransform>().sizeDelta = sizeDeltaForTexture;
            item.texture = texture;
        }
        if (save)
        {
            if(!string.IsNullOrEmpty(_UserEmail))
                SaveTextureToFile(texture, "ProfileImage_" + _UserEmail + ".jpg");
        }
    }
```
**Here are the logs from Android Logcat:**

there is one error, but it does not seem to me that it is because of this error.

![Logs](https://user-images.githubusercontent.com/71349845/149312606-42acd517-9064-4edd-a6f0-24bcf7972ca8.PNG)

And some examples:
the first couple of screenshots - when it doesn't rotate.
and the second couple of screenshots - when it is rotated.

![1 2](https://user-images.githubusercontent.com/71349845/149314317-4550c3c3-5509-4b66-9bda-259edfd2bbb5.jpg)
![1 1](https://user-images.githubusercontent.com/71349845/149314322-c87ad091-3a5a-4868-bbe9-209d318a8b9b.jpg)
------------------------------------------------------------------------------------------------------------------------------------
![2 2](https://user-images.githubusercontent.com/71349845/149314407-0f004a73-5dd6-4b2d-a38a-6385453b2544.jpg)
![2 1](https://user-images.githubusercontent.com/71349845/149314410-9716acaa-846d-42ec-bffe-26e0f9470ef9.jpg)

- Unity version: 2020.3.19f1
- Platform: Android, IOS
- I downloaded this asset from  GitHub a few days ago.

**Comment by yasirkula** [comment]
For picking image/video files, I'd highly suggest using [NativeGallery](https://github.com/yasirkula/UnityNativeGallery) instead. If you want to stick with NativeFilePicker, you should still use **NativeGallery.LoadImageAtPath** because that function will (should) rotate the image correctly if its EXIF orientation isn't portrait.

**Comment by DavianMachete** [comment]
@yasirkula thanks for the quick reply, but it is not solution for my problem, more, the process takes more time (application Hides and opens after when user select photo), Ty))
