### ISSUE TITLE
Incorrect file name when loading ai/eps files (application/postscript)

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeFilePicker#20]
Hi, it's me again) I'm trying to open Adobe vector files .ai and .eps, and their names are incorrectly modified after processed by your plugin, it adds ".ps" at the end of the name.
For example, when picking "AI.ai", the app receives "/storage/emulated/0/Android/data/com.PixelStudio/cache/AI.ai.ps".

There was a similar issue with "application/octet-stream" (https://github.com/yasirkula/UnityNativeFilePicker/issues/16), so I hope this can be also easily fixed.

For now, I've made a workaround with removing ".ps", so it's not a major issue.

Thanks and see ya!

**Comment by yasirkula** [comment]
Latest version shouldn't have this issue. Here's the source code: https://github.com/yasirkula/UnityNativeFilePicker/blob/a79341c8276a8a782c71e3fb5c59589312c94eda/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeFilePickerPickResultOperation.java#L190-L193

May ".ps" be somehow related to your app, or a leftover from one of your previous modifications to the plugin's source code (if any)?

**Comment by hippogamesunity** [comment]
Hi! Yes, you're right, this doesn't happen in the latest version.
