### ISSUE TITLE
PickMultipleFiles doesn't work on Target Mac/Pc

### ISSUE THREAD

**Issue by yaalisri** [yasirkula/UnityNativeFilePicker#23]
**Description of the bug**

` NativeFilePicker.PickMultipleFiles` method doesn't work and the file picker doesn't show up while we set the unity target platform to **Mac/PC** 

But `NativeFilePicker.PickFile` method works as expected. It shows a file picker using the Finder window and successfully picks a single file.

Below is my code to reproduce the bug, it prints "Operation cancelled" always.

 ```
string jpegFileType = NativeFilePicker.ConvertExtensionToFileType( "jpeg" ); // Returns "application/pdf" on Android and "com.adobe.pdf" on iOS
            string pngFileType = NativeFilePicker.ConvertExtensionToFileType( "png" ); // Returns "application/pdf" on Android and "com.adobe.pdf" on iOS

            Debug.Log( "pdf's MIME/UTI is: " + jpegFileType +  pngFileType);

            string[] fileTypes = new string[] { jpegFileType, pngFileType};
            // Pick image(s) and/or video(s)
            NativeFilePicker.Permission permission = NativeFilePicker.PickMultipleFiles( ( paths ) =>
            {
                if( paths == null )
                    Debug.Log( "Operation cancelled" );
                else
                {
                    for( int i = 0; i < paths.Length; i++ ) {
                         Debug.Log( "Picked file: " + paths[i] );
                    }
                }
            }, fileTypes);
```

**Platform specs**

- Unity version: 2020.3.27f1
- Platform: Mac, Windows
- How did you download the plugin: Package Manager

**Comment by yasirkula** [comment]
The editor functionality is for preview purposes only and uses EditorUtility.OpenFilePanelWithFilters which unfortunately doesn't support picking multiple files AFAIK.
