### ISSUE TITLE
Unable to build in Xcode 13

### ISSUE THREAD

**Issue by shyam-appymonkeys** [yasirkula/UnityNativeFilePicker#25]
When I try to build the app with Native File picker in it, Xcode throws an error in the NativeFilePicker.mm file.
I've attached screenshots of the error

<img width="730" alt="image" src="https://user-images.githubusercontent.com/47814360/176167179-e25b5f4e-9e20-4d31-8c58-f6fa04f9f1d4.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/47814360/176166837-8f239268-adcd-4e7f-8113-0f34f4394451.png">

**Comment by yasirkula** [comment]
Please delete the plugin and download it from GitHub. Asset Store is broken on some Unity versions (it doesn't actually download the asset's latest version) and you seem to have encountered the same problem because I've fixed this issue in an earlier release.

**Comment by shyam-appymonkeys** [comment]
Yes, this has worked.
