### ISSUE TITLE
No apps can perform this action

### ISSUE THREAD

**Issue by Isaac-dot** [yasirkula/UnityNativeFilePicker#26]
**Reproduction steps**
If I press the file load button, it will show "No apps can perform this action" like the following screen shot
![image](https://user-images.githubusercontent.com/72924991/187915286-dfa753cd-1a56-4712-8f1f-a4362cd76f18.png)
![image](https://user-images.githubusercontent.com/72924991/187915376-37eb1cbf-3ba0-4fe8-a3df-61531344446b.png)

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2018.3.1f1*
- Platform: *Android*
- Device: *MI 9 SE, Android 9*
- How did you download the plugin: * Asset Store*

**Additional info**
this is the button function.
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;

public class FilePickerSystem : MonoBehaviour
{
    public string FinalPath;

    public void LoadFile()
    {
        string FileType = NativeFilePicker.ConvertExtensionToFileType("*");
        NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) => 
        {
            if (path == null)
                Debug.Log("Operation cancelled");
            else
            {
                FinalPath = path;
                Debug.Log("Picked file: " + FinalPath);
            }
        }, new string[] { FileType });
    }
}
`

**Comment by yasirkula** [comment]
I don't think NativeFilePicker.ConvertExtensionToFileType("*") will work. On Android, you can pass a hardcoded `new string[] { "*/*" }` or `new string[] { "application/octet-stream" }` to PickFile.

**Comment by Isaac-dot** [comment]
@yasirkula  
thank you for reply, so sorry that i am not good at coding the code above is from online tutorial. could u explan that in detail

**Comment by yasirkula** [comment]
You can replace `new string[] { FileType })` with my suggestions (assuming this app won't be published on iOS).

**Comment by Isaac-dot** [comment]
ah ha it works. thank you so much. i used `string FileType = "*/*";` so this one only work on android right and if i would like to publish on iOS what should i change. and on android is it possible to just pick image file by using `string FileType = "png,jpg,jpeg";`

**Comment by yasirkula** [comment]
On iOS, I think you can try "public.data" or "public.content" as FileType. You can check Application.platform to switch its value depending on the platform.

To fetch image files only, I'd recommend using [NativeGallery](https://github.com/yasirkula/UnityNativeGallery) instead. If you'd still like to use NativeFilePicker, then:

```csharp
NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) => 
{
	if (path == null)
		Debug.Log("Operation cancelled");
	else
	{
		FinalPath = path;
		Debug.Log("Picked file: " + FinalPath);
	}
}, new string[] { NativeFilePicker.ConvertExtensionToFileType("png"), NativeFilePicker.ConvertExtensionToFileType("jpg") });
```

**Comment by Isaac-dot** [comment]
thanks alot. it works really well
