### ISSUE TITLE
Failed to download a file from google drive in Android

### ISSUE THREAD

**Issue by freeschool** [yasirkula/UnityNativeFilePicker#29]
Failed to download a file from google drive in Android

Selected media uri: content://com.google.android.apps.docs.storage/document/acc%3D2%3Bdoc%3Dencoded%3DP5tyQ4bvMAM8Z1PJO7DG_cI9csLiGixE5O26beuZYizmE_Gddd8qxPMDe7TcikW30XA%3D
10-10 11:00:51.327 21026 24029 E Unity   : Exception:
10-10 11:00:51.327 21026 24029 E Unity   : java.io.FileNotFoundException: StorageFileLoadException[io_error]
10-10 11:00:51.327 21026 24029 E Unity   :      at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
10-10 11:00:51.327 21026 24029 E Unity   :      at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
10-10 11:00:51.327 21026 24029 E Unity   :      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
10-10 11:00:51.327 21026 24029 E Unity   :      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
10-10 11:00:51.327 21026 24029 E Unity   :      at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
10-10 11:00:51.327 21026 24029 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultOperation.copyToTempFile(NativeFilePickerPickResultOperation.java:215)
10-10 11:00:51.327 21026 24029 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultOperation.getPathFromURI(NativeFilePickerPickResultOperation.java:157)
10-10 11:00:51.327 21026 24029 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultOperation.execute(NativeFilePickerPickResultOperation.java:53)
10-10 11:00:51.327 21026 24029 E Unity   :      at com.yasirkula.unity.NativeFilePickerPickResultFragment$2.run(NativeFilePickerPickResultFragment.java:83)
10-10 11:00:51.327 21026 24029 E Unity   :      at java.lang.Thread.run(Thread.java:920)

The file is in the google drive and the internet is working.

How can I fix this? this randomly happends. Some files are downloadable some files throw the error message above.

Unity 2021.3.

**Comment by yasirkula** [comment]
Could you update Drive to latest version: https://issuetracker.google.com/issues/230454569

**Comment by freeschool** [comment]
Thank you for the quick answer.
I had the latest version of Google Drive. The plugin was not working with the latest. 
Simply, I reinstalled the Drive then works fine now.
I really appreciate it.
