### ISSUE TITLE
Yet another "No apps can perform this action"

### ISSUE THREAD

**Issue by shielrp** [yasirkula/UnityNativeFilePicker#32]
**Description of the bug**

A small subset of our users, seemingly only on Android, receive the "No apps can perform this action" message when trying to use the function that invokes `PickFile`. The filetype being selected is a JSON file. We've been unable to reproduce the issue in-house.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.3.27f1
- Platform: Android, possibly iOS
- How did you download the plugin: Asset Store

**Additional info**

Here is some relevant parts of the code in question.

```cs
var allowedTypes = new string[] { NativeFilePicker.ConvertExtensionToFileType("json") };

var permission = NativeFilePicker.PickFile((pth) =>
{
   //callback content
}, allowedTypes);
```

It's worth mentioning that this is happening with version 1.29 of NativeFilePicker. We are working to release an update that upgrades the package to 1.30, but have not been able to test this issue in that update as of yet.

**Comment by yasirkula** [comment]
I don't think 1.30 will help with this issue. You can try hardcoding "application/json" as allowedTypes' value rather than using ConvertExtensionToFileType to see if that function fails but I don't think that's the culprit. I wonder if any other file type like "txt" work correctly on those devices. Perhaps they are rooted or uncommon devices with no file browser installed which thus don't have the functionality to pick files with that nonexisting file browser.

**Comment by shielrp** [comment]
Thanks a ton, I appreciate the leads! I'll add that code to the game, and I'll see if getting a decent file browser on a users phone will solve the issue.

**Comment by shielrp** [comment]
I ended up resolving this issue by adding `NativeFilePicker.ConvertExtensionToFileType("txt")` to the `allowedTypes` array, and by changing future exported files to have a .txt extension. The picker now shows on affected phones, but is unable to select .json files. If the files are changed to have a .txt extension, they are selected fine.

I could have done this without changing the exported file extension, but I'm just trying to head off having to provide a solution to folks in the future.

Thanks for the insight, I couldn't have fixed it without you! Or built this feature at all for that matter!

**Comment by yasirkula** [comment]
Thank you for sharing your findings! Did you try hardcoding "application/json" as allowedTypes before switching to txt?

**Comment by shielrp** [comment]
I didn't, sorry. I'll add that in a future release and see if I can test it for you.

**Comment by yasirkula** [comment]
Try `var allowedTypes = new string[] { "*/*" };` instead.

**Comment by yasirkula** [comment]
I don't think there is a such filter on either Mac or Windows :/

**Comment by marcusx2** [comment]
What's the allowed type for any file on iOS? I tried the "*/*", it works on Android, but on iOS the files show up but I can't select them..

**Comment by yasirkula** [comment]
@marcusx2 I'd set it to the following array but I haven't tried it: `new string[] { "public.item", "public.content" }`
