### ISSUE TITLE
ability to extend video extensions list (adding mkv)

### ISSUE THREAD

**Issue by jakedowns** [yasirkula/UnityNativeFilePicker#36]
https://github.com/yasirkula/UnityNativeFilePicker/blame/634be9b273404124e6f707a6228afe7c1c924815/Plugins/NativeFilePicker/NativeFilePicker.cs#L215

hey there, thanks for a great package

wanted to note that i had to go in and edit this file in my project to add "mkv" video file support

i know that's pretty non-standard, but it could be helpful to have a way to extend the list of file extensions.

could also be nice to have a broader type that could accept video or images, or even audio simultaneously, for media player apps.

**Comment by yasirkula** [comment]
Hi! That extension list is valid for Unity editor only, it has no effect in a built game. So even though the suggested changes are all valid for a file explorer, in this case they're not essential.
