### ISSUE TITLE
Can not get the real path but a sandbox cache path

### ISSUE THREAD

**Issue by Bian-Sh** [yasirkula/UnityNativeFilePicker#38]
**Description of the bug**
我的文件存在 Download 文件夹，路径如下：
```
storage/emulated/0/Download/MyFolder/myjson.json
```
但是这个插件读取到的路径却是在应用的  Application.persistentDataPath 路径下的 cache 文件夹下，路径如下
```
/storage/emulated/0/Android/data/com.<app id>/cache/cover.png
```
请问这是预期和合理的吗？
如果不是预期的，怎么获得真实的路径呢？
我看了 Readme，但是不知道你描述的问题是不是我这个问题。

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2021.3.1f1*
- Platform: *Android*
- Device: *Oppo K10 5G*
- How did you download the plugin: *GitHub repo not from release tab*

**Comment by yasirkula** [comment]
Hi, that's the same limitation that's described in FAQ, unfortunately:

> - **How can I fetch the path of the saved file or the original path of the picked file?**
> 
> You can't. The abstraction layers used on each platform deliberately don't return raw file paths.

**Comment by Bian-Sh** [comment]
谢谢！
