### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [yasirkula/UnityNativeFilePicker#4]
**Description of the bug**

Git tag 1.2.1
package.json 1.2.0

https://github.com/yasirkula/UnityNativeFilePicker/blob/6a50f24e7f650823a95e828e7c964611339dcda9/package.json

package.json@master: 1.2.1

**How to fix it?**
Re-tag 1.2.1 from the master branch.

**Comment by yasirkula** [comment]
Recreated the 1.2.1 release. Hope it resolves the issue.

**Comment by favoyang** [comment]
It works! Thank you for fixing it.

![image](https://user-images.githubusercontent.com/125390/97438812-47609980-1960-11eb-8777-68efed01b599.png)

https://openupm.com/packages/com.yasirkula.nativefilepicker/?subPage=pipelines

**Comment by yasirkula** [comment]
@favoyang I've noticed that on my IngameDebugConsole repository, [OpenUPM version 1.4.1](https://openupm.com/packages/com.yasirkula.ingamedebugconsole/?subPage=versions) is stuck at an early commit even though I've [recreated that release](https://github.com/yasirkula/UnityIngameDebugConsole/releases/tag/v1.4.1) after a couple of additional commits. What might be happening?

**Comment by favoyang** [comment]
Hi @yasirkula,

Yes, the [build pipelines](https://openupm.com/packages/com.yasirkula.ingamedebugconsole/?subPage=pipelines) show it already published 1.4.1 based on https://github.com/yasirkula/UnityIngameDebugConsole/commit/4cbe93c28683bb71e668ba202c5be023d44102e2.

The build pipelines won't republish published content. So even you re-tag it, it won't affect our registry. You have to bump the version to fix it.

Here's a discussion about the policy, with more detailed information https://github.com/openupm/openupm/discussions/1906
