### ISSUE TITLE
Empty window when trying to open a file on Android

### ISSUE THREAD

**Issue by Son1kXDev** [yasirkula/UnityNativeFilePicker#40]
**Description of the bug**

I'm trying to make an image upload to my android game. When I check everything in Unity, everything works fine - a file selection window opens and the files are successfully uploaded. But when building on android, something strange happens: an empty window opens with a single "Cancel" button and nothing else happens. At the same time, the message is displayed in the logs for the first time: "Timeout while trying to pause the Unity Engine.", and all subsequent times nothing is output, while the game continues to work calmly.

![photo_2023-04-23_23-01-43](https://user-images.githubusercontent.com/106654105/233862788-df7dd2fd-d3be-4a5d-ad10-2de47182ee78.jpg)

Here is my code:
```
    public void LoadFile(System.Action<string> callback, System.Action<bool> success)
    {
        string FileType = NativeFilePicker.ConvertExtensionToFileType("image/*");

        NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) =>
        {
            if (path == null) success.Invoke(false);
            else
            {
                _path = path;
                SaveLoadedFile();
                callback.Invoke(LocalPath);
                success.Invoke(true);
                Debug.Log("Picked file " + path);
            }
        }, new string[] { FileType });
    }

    public void SaveLoadedFile()
    {
        string fileExtension = Path.GetExtension(_path);
        LocalPath = Path.Combine(Application.persistentDataPath, "sticker" + fileExtension);

        PlayerPrefs.SetString("StickerExtension", fileExtension);

        var bytes = File.ReadAllBytes(_path);

        File.WriteAllBytes(LocalPath, bytes);
    }
```

**Platform specs**

- Unity version: *e.g. 2021.3.18f1*
- Platform: Android
- Device: Xiaomi MI 12T, Android 13
- How did you download the plugin: Asset Store

**Additional info**
Timeout while trying to pause the Unity Engine.

**Comment by yasirkula** [comment]
Please use `string FileType = "image/*";` instead (Android only).
