### ISSUE TITLE
[Android]The callback of PickFile() function takes a null value after a file is picked

### ISSUE THREAD

**Issue by Newaser** [yasirkula/UnityNativeFilePicker#42]
The code is shown below
`string filePath = null;
// Pick an image
NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) =>
{
    if (path == null)
        Debug.Log("Operation cancelled");
    else
    {
        Debug.Log("Picked file: " + path);
        filePath = path;
    }
}, new string[] { "image/*" });
Debug.Log("Permission result: " + permission);
return filePath;`
This is the body of a method, and its return value is null
Once this code block is activated, an Android native file pick pops up successfully, and I can then pick an image file successfully,
but `path` is null eventually

**Comment by yasirkula** [comment]
I think you can find the "_Picked file_" log in logcat. The issue is, PickFile is asynchronous but you're trying to get a value from it synchronously (`return filePath;`). This is not possible. You have to execute your code after the "_Picked file_" log, inside that callback function.

**Comment by Newaser** [comment]
Thanks for your guide, I solved this problem by following your steps
