### ISSUE TITLE
Can't access csv file

### ISSUE THREAD

**Issue by Venomfire15** [yasirkula/UnityNativeFilePicker#45]
I am using the file to access the csv file from Android the file, it works properly in unity editor but when i try this on Android after build it doesn't open the csv file, it shows the file but doesn't open

**Comment by yasirkula** [comment]
.csv isn'a known file type according to [this list](http://androidxref.com/4.4.4_r1/xref/frameworks/base/media/java/android/media/MediaFile.java#174). The best you can do is, [allow selecting all files](https://forum.unity.com/threads/native-file-picker-for-android-ios-open-source.912890/page-3#post-8987518) and then verify that a csv file is selected.

**Comment by Venomfire15** [comment]
Thank you for the support, After doing the steps as you mentioned the problem is solved and code works correctly
