### ISSUE TITLE
Can I import or export a file of type [.dat]?

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityNativeFilePicker#5]
Can I import or export a file of type [.dat]?
![000000018](https://user-images.githubusercontent.com/50401776/99924559-cdaca780-2d75-11eb-897f-341bdc8cdbd8.gif)

**Comment by yasirkula** [comment]
On iOS, you can define custom file extensions: https://github.com/yasirkula/UnityNativeFilePicker#ios-setup. On Android, I think your best bet is to use `*/*` as allowed file type.

**Comment by ShenKang4181** [comment]
ok,love you
