### ISSUE TITLE
Sharing violation exception when replace a file in the Editor

### ISSUE THREAD

**Issue by vNikolenkoMIF** [yasirkula/UnityNativeFilePicker#50]
**Description:**
When I try to replace a file, system throws "sharing violation" exception.

**Log trace**

> IOException: Sharing violation on path "filepath"
> System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> NativeFilePicker.ExportFile (System.String filePath, NativeFilePicker+FilesExportedCallback callback) (at Library/PackageCache/com.yasirkula.nativefilepicker@337016a84b/Plugins/NativeFilePicker/NativeFilePicker.cs:341)
> UnityEngine.Debug:LogException(Exception)
> NativeFilePicker:ExportFile(String, FilesExportedCallback) (at Library/PackageCache/com.yasirkula.nativefilepicker@337016a84b/Plugins/NativeFilePicker/NativeFilePicker.cs:348)

**How to reproduce**

1. Export some file with help `NativePicker.ExportFile( string filePath, FilesExportedCallback callback = null )`
2. Export file one more time with same extension.
3. Select any file to make replace instead export and click on button Save in the file explorer menu.
4. Click on Yes button in "Replace file" menu.
5. Export will fail with exception.

**Platform specs**

- Unity version: 2020.3.20f1 LTS
- Platform: Unity Editor
- Asset version is 1.3.2

**Comment by yasirkula** [comment]
Can you reproduce this issue for files on Desktop or files inside your Unity project's Temp/Library folders?

**Comment by vNikolenkoMIF** [comment]
Oh, I am sorry, I have tested this case and that exception throws only in case when you try to replace file in the directory where this file was before. My fault.

**Comment by yasirkula** [comment]
You're welcome :) Note that this plugin doesn't support standalone platforms in a build. Only Android & iOS are supported. Editor partially supports it for preview purposes only.

**Comment by vNikolenkoMIF** [comment]
Oh, yes, I know, I am using your plugin for iOS & Android platform only, it works perfect. Thank you for quick response 👍
