### ISSUE TITLE
Script throwing and failing somewhere

### ISSUE THREAD

**Issue by Pietrodjaowjao** [yasirkula/UnityNativeFilePicker#54]
**Description of the bug**

I cant import any file, the import file script will throw somewhere and will just cancel the operation.
Methods used:
```
    public void OpenExplorerAndCopyDLL()
    {
        if (IsFilePickerBusy())
            return;

        string pickedFile = "";
        string dllFileType = ConvertExtensionToFileType("dll");
        Permission permission = PickFile((path) =>
        {
            if (path == null)
            {
                Debug.Log("Operation cancelled");
            }
            pickedFile = path;
        }, new string[] { dllFileType });

        Debug.Log(pickedFile);
        if (string.IsNullOrEmpty(pickedFile))
        {
            Debug.Log("Picked file is null (somehow)?");
            return;
        }

        CloneFile($"{Constants.ModsFolder()}/{Path.GetFileName(pickedFile)}", pickedFile);
    }
```

```
    void CloneFile(string destinationPath, string sourcePath)
    {
        Debug.Log(sourcePath);
        if (File.Exists(destinationPath))
        {
            File.Delete(destinationPath);
        }

        using (FileStream fs = File.Create(destinationPath))
        {
            byte[] bytes = File.ReadAllBytes(sourcePath);
            fs.Write(bytes, 0, bytes.Length);
        }

        Debug.Log("File cloned successfully.");
    }
```

**Reproduction steps**

If possible, providing reproduction steps would be very helpful while pinpointing the issue. You can also post screenshots if you think they would be helpful.

- Open game
- Try to import a dll file
- fail miserably

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2020.3.45f1*
- Platform: Android
- Device: Poco X6 Pro, Bluestacks 5 (Android 11)
- How did you download the plugin: Asset store

**Additional info**

Please check Logcat (Android) or Xcode console (iOS) for any meaningful error messages and include them here.
```
2024/05/13 01:00:50.603 16526 16526 Error ActivityThread  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
```

**Comment by Pietrodjaowjao** [comment]
Btw, the script will throw exactly in PickFile, so ```Debug.Log(pickedFile);``` and everything after this will not even run at all

**Comment by yasirkula** [comment]
Does this work:

```csharp
public void OpenExplorerAndCopyDLL()
{
	if (IsFilePickerBusy())
		return;

	string dllFileType = ConvertExtensionToFileType("dll");
	Permission permission = PickFile((path) =>
	{
		if (path == null)
		{
			Debug.Log("Operation cancelled");
		}
		else
		{
			CloneFile($"{Constants.ModsFolder()}/{Path.GetFileName(path)}", path);
		}
		pickedFile = path;
	}, new string[] { dllFileType });
}
```

**Comment by Pietrodjaowjao** [comment]
Seems to work in android and unity editor for windows , but in windows executable the file picker is not opening anymore

**Comment by yasirkula** [comment]
Yes because only Android & iOS platforms are supported. There are native and uGUI alternatives for standalone platforms.
