### ISSUE TITLE
IOS Xcode Build errors with manual setup: Undefined symbols for architecture arm64:   "_kUTTagClassFilenameExtension"

### ISSUE THREAD

**Issue by ROBYER1** [yasirkula/UnityNativeFilePicker#9]
**Description of the bug**

When using Automatic IOS build setup, the plugin works fine, however I have a project where I need to use a push notification service so I switched over to manual steps. I found that when doing them, I get this error:

`Undefined symbols for architecture arm64:
  "_kUTTagClassFilenameExtension", referenced from:
      +[UNativeFilePicker convertExtensionToUTI:] in NativeFilePicker.o
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      +[UNativeFilePicker convertExtensionToUTI:] in NativeFilePicker.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

So I went and made a fresh project just imported UnityNativeFilePicker and tried again there, same error!

I think this is a fantastic plugin and want to be able to use it for a few apps if there is a fix for this error?

I suspect something changed in Xcode recently for this issue to happen? 

**Reproduction steps**

Repro Project: https://drive.google.com/file/d/1Ke8xfR77bywc9OawG3nJZjThfcayZDef/view?usp=sharing

Open this repro project in Unity 2020.3.0f1 on a mac with Xcode 12.4 installed, build the project, follow the manual IOS steps here: https://github.com/yasirkula/UnityNativeFilePicker/wiki/Manual-Setup-for-iOS

**Platform specs**

I am using Unity 2020.3.0f1 on MacOS Big Sur 11.2.3, Xcode 12.4 and build target is an Ipad running IOS 14~
Plugin downloaded via the Git URL through package manager

**Additional info**
Screenshots just to make sure I'm not missing anything here:

<img width="818" alt="Screenshot 2021-03-26 at 17 33 31" src="https://user-images.githubusercontent.com/10745594/112670886-656fee80-8e59-11eb-9752-1f8c067268cb.png">

<img width="494" alt="Screenshot 2021-03-26 at 17 31 38" src="https://user-images.githubusercontent.com/10745594/112670786-44a79900-8e59-11eb-9f77-6dc4cbd9fec2.png">

**Comment by yasirkula** [comment]
Thank you for the detailed Issue. I don't have access to a Mac workstation for a while; the last time I remember, "Link Binary With Libraries" list was full of random frameworks filled by Unity. I wonder why there is only 1 framework there in your screenshot. But that is irrelevant. Can you try adding CloudKit framework? If issue persists, SystemConfiguration framework?

**Comment by ROBYER1** [comment]
Thanks for the quick response, I tried adding those one by one and still had the same build errors, is there anything else I can try to fix it?

The reason that list is empty is because it's basically an empty unity project I made to reproduce this issue, and this project build/runs just fine when using the automatic IOS setup through the Postbuildprocessor script in your package
<img width="1113" alt="Screenshot 2021-03-26 at 19 33 08" src="https://user-images.githubusercontent.com/10745594/112683830-19797580-8e6a-11eb-8404-22283cb2cc0e.png">

**Comment by yasirkula** [comment]
Can you add these frameworks to UnityFramework one by one?

**Comment by ROBYER1** [comment]
I just found the fix! In the guide for manual steps it says:
"add MobileCoreServices.framework to Link Binary With Libraries list in Build Phases", this is not clear as the screenshots show the Unity-Iphone Target selected on the left, one would assume you link the MobileCoreServices.framework to there - but you actually need to link it to the target 'UnityFramework' in that target's Build Phases - Link Binary With Libraries list.

When you mentioned the list of frameworks was short, I realised then your process was for one of the targets that had a big list of frameworks linked.

Can I suggest you update the manual steps guide here with the mention that it needs to be done in the Targets - UnityFramework Build Phases, no the default Unity-Iphone target? Even just a screenshot like mine there makes it clear that you need to click on a different target

I will post this fix back on the Unity Forum also as I saw another member having the same issue as me there too

One last question also, is there a tidy way to automate that step of linking that framework without breaking other plugins that may edit the plist file/other settings on build, or is it just safest to follow the manual steps everytime in Xcode after a build

<img width="888" alt="Screenshot 2021-03-26 at 19 37 41" src="https://user-images.githubusercontent.com/10745594/112684328-cb18a680-8e6a-11eb-9ebd-62e3fa12b9cf.png">

**Comment by yasirkula** [comment]
I've updated the wiki. To just add the framework automatically, you can comment out these lines: https://github.com/yasirkula/UnityNativeFilePicker/blob/f15e56ab05fecb61ca92ba85dccbb34e6f6dd968/Plugins/NativeFilePicker/Editor/NativeFilePickerPostProcessBuild.cs#L122-L135

**Comment by ROBYER1** [comment]
Thank you! This bug is resolved
